[workspace]
members = ["vst3-host", "vst3-inspector"]
resolver = "2"

# Shared dependencies for the workspace
[workspace.dependencies]
vst3 = "0.1.2"
log = "0.4"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"