[package]
name = "vst3-host"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"
description = "A safe, simple, and lightweight Rust library for hosting VST3 plugins"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/vst3-host"
keywords = ["vst3", "audio", "plugin", "host", "midi"]
categories = ["multimedia::audio", "api-bindings"]

[dependencies]
vst3 = "0.1"
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
log = "0.4"

# Optional dependencies
cpal = { version = "0.15", optional = true }
egui = { version = "0.30", optional = true }

# Platform-specific dependencies
[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
objc = "0.2"
core-foundation = "0.10"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winuser", "windef", "libloaderapi"] }

[features]
default = ["cpal-backend", "process-isolation"]
cpal-backend = ["cpal"]
process-isolation = []
egui-widgets = ["egui"]

[dev-dependencies]
env_logger = "0.11"

[[example]]
name = "basic_host"
required-features = ["cpal-backend"]

[[example]]
name = "plugin_scanner"

[[example]]
name = "midi_keyboard"
required-features = ["cpal-backend"]